### ISSUE TITLE
Rebrand - Fix Github Actions workflow to push changes to site

### ISSUE THREAD

**Issue by TheBookKnight** [TheBookKnight/thebookknight.github.io#9]
After PR https://github.com/TheBookKnight/thebookknight.github.io/pull/8 

The website deployment broke and produced the below error. There seems to be a limitation on Ruby versions. 
```
[build](https://github.com/TheBookKnight/thebookknight.github.io/actions/runs/11905442323/job/33175932213#step:3:8)
Error: Unknown version 3.3.5 for ruby on ubuntu-22.04
        available versions for ruby on ubuntu-22.04: 1.9.3-p551, 2.0.0-p648, 2.1.9, 2.2.10, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.3.6, 2.3.7, 2.3.8, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.4.5, 2.4.6, 2.4.7, 2.4.9, 2.4.10, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.5.4, 2.5.5, 2.5.6, 2.5.7, 2.5.8, 2.5.9, 2.6.0, 2.6.1, 2.6.2, 2.6.3, 2.6.4, 2.6.5, 2.6.6, 2.6.7, 2.6.8, 2.6.9, 2.6.10, 2.7.0, 2.7.1, 2.7.2, 2.7.3, 2.7.4, 2.7.5, 2.7.6, 2.7.7, 2.7.8, 3.0.0-preview1, 3.0.0-preview2, 3.0.0-rc1, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.1.0-preview1, 3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.1.4, 3.2.0-preview1, 3.2.0-preview2, 3.2.0-preview3, 3.2.0-rc1, 3.2.0, 3.2.1, 3.2.2, 3.3.0-preview1, 3.3.0-preview2, 3.3.0-preview3, head, debug
        Make sure you use the latest version of the action with - uses: ruby/setup-ruby@v1
    at validateRubyEngineAndVersion (/home/runner/work/_actions/ruby/setup-ruby/8575951200e472d5f2d95c625da0c7bec8217c42/dist/index.js:65857:13)
    at setupRuby (/home/runner/work/_actions/ruby/setup-ruby/8575951200e472d5f2d95c625da0c7bec8217c42/dist/index.js:65758:19)
    at run (/home/runner/work/_actions/ruby/setup-ruby/8575951200e472d5f2d95c625da0c7bec8217c42/dist/index.js:65722:11)
    at /home/runner/work/_actions/ruby/setup-ruby/8575951200e472d5f2d95c625da0c7bec8217c42/dist/index.js:65891:40
    at /home/runner/work/_actions/ruby/setup-ruby/8575951200e472d5f2d95c625da0c7bec8217c42/dist/index.js:65893:3
    at Object.<anonymous> (/home/runner/work/_actions/ruby/setup-ruby/8575951200e472d5f2d95c625da0c7bec8217c42/dist/index.js:65896:12)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
```

**Comment by TheBookKnight** [comment]
This is the latest supported Github-hosted ubuntu runners
https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories 

And this is the ubuntu images supported by the ruby setup Github action
https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby#supported-platforms

So, I'll have to set a specific version for ubuntu

**Comment by TheBookKnight** [comment]
Nevermind, perhaps it can support `3.3.5`
https://github.com/ruby/setup-ruby/blob/master/ruby-builder-versions.json 

But, maybe I need to use a Ruby's `@v1` and use latest ubuntu image.

**Comment by TheBookKnight** [comment]
Got this error
```
Your bundle only supports platforms ["x86_64-darwin-19", "x86_64-darwin-23",
"x86_64-linux-musl"] but your local platform is x86_64-linux. Add the current
platform to the lockfile with
`bundle lock --add-platform x86_64-linux` and try again.
Error: The process '/opt/hostedtoolcache/Ruby/3.3.5/x64/bin/bundle' failed with exit code 16
```

**Comment by TheBookKnight** [comment]
So, I solved the above error with https://stackoverflow.com/a/75194031 

But, I got a new error
```
Configuration file: /home/runner/work/thebookknight.github.io/thebookknight.github.io/_config.yml
To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
            Source: /home/runner/work/thebookknight.github.io/thebookknight.github.io
       Destination: /home/runner/work/thebookknight.github.io/thebookknight.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
             Error: could not read file /home/runner/work/thebookknight.github.io/thebookknight.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-3.[10](https://github.com/TheBookKnight/thebookknight.github.io/actions/runs/11905641967/job/33176460277#step:5:11).0/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb: Invalid date '<%= Time.now.strftime('%Y-%m-%d %H:%M:%S %z') %>': Document 'vendor/bundle/ruby/3.3.0/gems/jekyll-3.10.0/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb' does not have a valid date in the YAML front matter.
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    Invalid date '<%= Time.now.strftime('%Y-%m-%d %H:%M:%S %z') %>': Document 'vendor/bundle/ruby/3.3.0/gems/jekyll-3.10.0/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb' does not have a valid date in the YAML front matter.
Error: Process completed with exit code 1.
```

**Comment by TheBookKnight** [comment]
Ok, so I'm getting something different with solution from https://github.com/jekyll/jekyll/issues/5267#issuecomment-241379902 

I got this error instead
```
Incremental build: disabled. Enable with --incremental
      Generating... 
   GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
   GitHub Metadata: GET https://api.github.com/repos/TheBookKnight/neumorphism/contributors?per_page=100: 403 - API rate limit exceeded for 20.172.29.17. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting
   GitHub Metadata: GET https://api.github.com/repos/TheBookKnight/pdf-diff-tool/releases?per_page=100: 403 - API rate limit exceeded for 20.172.29.17. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting
   GitHub Metadata: GET https://api.github.com/repos/TheBookKnight/pdf-diff-tool/contributors?per_page=100: 403 - API rate limit exceeded for 20.172.29.17. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting
   GitHub Metadata: GET https://api.github.com/repos/TheBookKnight/Pin-It/releases?per_page=100: 403 - API rate limit exceeded for 20.172.29.17. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting
   GitHub Metadata: GET https://api.github.com/repos/TheBookKnight/Pin-It/contributors?per_page=100: 403 - API rate limit exceeded for 20.172.29.17. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting
   GitHub Metadata: GET https://api.github.com/repos/TheBookKnight/pokemon-react/releases?per_page=100: 403 - API rate limit exceeded for 20.172.29.17. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting
   GitHub Metadata: GET https://api.github.com/repos/TheBookKnight/pokemon-react/contributors?per_page=100: 403 - API rate limit exceeded for 20.172.29.17. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting
   GitHub Metadata: GET https://api.github.com/repos/TheBookKnight/pokemon-react-web/releases?per_page=100: 403 - API rate limit exceeded for 20.172.29.17. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting
   GitHub Metadata: GET https://api.github.com/repos/TheBookKnight/pokemon-react-web/contributors?per_page=100: 403 - API rate limit exceeded for 20.172.29.17. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting
   GitHub Metadata: GET https://api.github.com/repos/TheBookKnight/pokemondata/releases?per_page=100: 403 - API rate limit exceeded for 20.172.29.17. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting
   GitHub Metadata: GET https://api.github.com/repos/TheBookKnight/pokemondata/contributors?per_page=100: 403 - API rate limit exceeded for 20.172.29.17. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting
   GitHub Metadata: GET https://api.github.com/repos/TheBookKnight/protractor-jasmine-cucumber/releases?per_page=100: 403 - API rate limit exceeded for 20.172.29.17. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting
   GitHub Metadata: GET https://api.github.com/repos/TheBookKnight/protractor-jasmine-cucumber/contributors?per_page=100: 403 - API rate limit exceeded for 20.172.29.17. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting
   GitHub Metadata: GET https://api.github.com/repos/TheBookKnight/PyTestDemo/releases?per_page=100: 403 - API rate limit exceeded for 20.172.29.17. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting
   GitHub Metadata: GET https://api.github.com/repos/TheBookKnight/PyTestDemo/contributors?per_page=100: 403 - API rate limit exceeded for 20.172.29.17. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting
   GitHub Metadata: GET https://api.github.com/repos/TheBookKnight/Python-Fragments/releases?per_page=100: 403 - API rate limit exceeded for 20.172.29.17. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting
   GitHub Metadata: GET https://api.github.com/repos/TheBookKnight/Python-Fragments/contributors?per_page=100: 403 - API rate limit exceeded for 20.172.29.17. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting
   GitHub Metadata: GET https://api.github.com/repos/TheBookKnight/PythonTestDemo/releases?per_page=100: 403 - API rate limit exceeded for 20.172.29.17. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting
   GitHub Metadata: GET https://api.github.com/repos/TheBookKnight/PythonTestDemo/contributors?per_page=100: 403 - API rate limit exceeded for 20.172.29.17. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting
   GitHub Metadata: GET https://api.github.com/repos/TheBookKnight/python_google/releases?per_page=100: 403 - API rate limit exceeded for 20.172.29.17. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting
   GitHub Metadata: GET https://api.github.com/repos/TheBookKnight/python_google/contributors?per_page=100: 403 - API rate limit exceeded for 20.172.29.17. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting
   GitHub Metadata: GET https://api.github.com/repos/TheBookKnight/python_selenium_shoprite/releases?per_page=100: 403 - API rate limit exceeded for 20.172.29.17. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting
   GitHub Metadata: GET https://api.github.com/repos/TheBookKnight/python_selenium_shoprite/contributors?per_page=100: 403 - API rate limit exceeded for 20.172.29.17. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting
   GitHub Metadata: GET https://api.github.com/repos/TheBookKnight/react-native-rpg/releases?per_page=100: 403 - API rate limit exceeded for 20.172.29.17. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting
   GitHub Metadata: GET https://api.github.com/repos/TheBookKnight/react-native-rpg/contributors?per_page=100: 403 - API rate limit exceeded for 20.172.29.17. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting
   GitHub Metadata: GET https://api.github.com/repos/TheBookKnight/react-native-thunk-practice/releases?per_page=100: 403 - API rate limit exceeded for 20.172.29.17. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting
   GitHub Metadata: GET https://api.github.com/repos/TheBookKnight/react-native-thunk-practice/contributors?per_page=100: 403 - API rate limit exceeded for 20.172.29.17. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting
   GitHub Metadata: GET https://api.github.com/repos/TheBookKnight/react-redux-practice/releases?per_page=100: 403 - API rate limit exceeded for 20.172.29.17. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting
   GitHub Metadata: GET https://api.github.com/repos/TheBookKnight/react-redux-practice/contributors?per_page=100: 403 - API rate limit exceeded for 20.172.29.17. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting
   GitHub Metadata: GET https://api.github.com/repos/TheBookKnight/react-tictactoe-app/releases?per_page=100: 403 - API rate limit exceeded for 20.172.29.17. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting
   GitHub Metadata: GET https://api.github.com/repos/TheBookKnight/react-tictactoe-app/contributors?per_page=100: 403 - API rate limit exceeded for 20.172.29.17. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting
   GitHub Metadata: GET https://api.github.com/repos/TheBookKnight/redux-essentials-example-app/releases?per_page=100: 403 - API rate limit exceeded for 20.172.29.17. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting
   GitHub Metadata: GET https://api.github.com/repos/TheBookKnight/redux-essentials-example-app/contributors?per_page=100: 403 - API rate limit exceeded for 20.172.29.17. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting
   GitHub Metadata: GET https://api.github.com/repos/TheBookKnight/redux-fundamentals-example-app/releases?per_page=100: 403 - API rate limit exceeded for 20.172.29.17. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting
   GitHub Metadata: GET https://api.github.com/repos/TheBookKnight/redux-fundamentals-example-app/contributors?per_page=100: 403 - API rate limit exceeded for 20.172.29.17. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting
   GitHub Metadata: GET https://api.github.com/repos/TheBookKnight/Reset/releases?per_page=100: 403 - API rate limit exceeded for 20.172.29.17. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting
	from /home/runner/work/thebookknight.github.io/thebookknight.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-3.10.0/lib/jekyll/site.rb:472:in `block in render_pages'
	from /home/runner/work/thebookknight.github.io/thebookknight.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-3.10.0/lib/jekyll/site.rb:471:in `each'
	from /home/runner/work/thebookknight.github.io/thebookknight.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-3.10.0/lib/jekyll/site.rb:471:in `render_pages'
	from /home/runner/work/thebookknight.github.io/thebookknight.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-3.10.0/lib/jekyll/site.rb:192:in `render'
	from /home/runner/work/thebookknight.github.io/thebookknight.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-3.10.0/lib/jekyll/site.rb:71:in `process'
	from /home/runner/work/thebookknight.github.io/thebookknight.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-3.10.0/lib/jekyll/command.rb:28:in `process_site'
	from /home/runner/work/thebookknight.github.io/thebookknight.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-3.10.0/lib/jekyll/commands/build.rb:65:in `build'
	from /home/runner/work/thebookknight.github.io/thebookknight.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-3.10.0/lib/jekyll/commands/build.rb:36:in `process'
	from /home/runner/work/thebookknight.github.io/thebookknight.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-3.10.0/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /home/runner/work/thebookknight.github.io/thebookknight.github.io/vendor/bundle/ruby/3.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	from /home/runner/work/thebookknight.github.io/thebookknight.github.io/vendor/bundle/ruby/3.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	from /home/runner/work/thebookknight.github.io/thebookknight.github.io/vendor/bundle/ruby/3.3.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	from /home/runner/work/thebookknight.github.io/thebookknight.github.io/vendor/bundle/ruby/3.3.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	from /home/runner/work/thebookknight.github.io/thebookknight.github.io/vendor/bundle/ruby/3.3.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	from /home/runner/work/thebookknight.github.io/thebookknight.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-3.10.0/exe/jekyll:15:in `<top (required)>'
	from /home/runner/work/thebookknight.github.io/thebookknight.github.io/vendor/bundle/ruby/3.3.0/bin/jekyll:25:in `load'
	from /home/runner/work/thebookknight.github.io/thebookknight.github.io/vendor/bundle/ruby/3.3.0/bin/jekyll:25:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.3.5/x64/lib/ruby/gems/3.3.0/gems/bundler-2.3.14/lib/bundler/cli/exec.rb:58:in `load'
	from /opt/hostedtoolcache/Ruby/3.3.5/x64/lib/ruby/gems/3.3.0/gems/bundler-2.3.14/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /opt/hostedtoolcache/Ruby/3.3.5/x64/lib/ruby/gems/3.3.0/gems/bundler-2.3.14/lib/bundler/cli/exec.rb:23:in `run'
	from /opt/hostedtoolcache/Ruby/3.3.5/x64/lib/ruby/gems/3.3.0/gems/bundler-2.3.14/lib/bundler/cli.rb:483:in `exec'
	from /opt/hostedtoolcache/Ruby/3.3.5/x64/lib/ruby/gems/3.3.0/gems/bundler-2.3.14/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /opt/hostedtoolcache/Ruby/3.3.5/x64/lib/ruby/gems/3.3.0/gems/bundler-2.3.14/lib/bundler/vendor/thor/lib/thor/invocation.rb:[12](https://github.com/TheBookKnight/thebookknight.github.io/actions/runs/11905698311/job/33176602330#step:5:13)7:in `invoke_command'
	from /opt/hostedtoolcache/Ruby/3.3.5/x64/lib/ruby/gems/3.3.0/gems/bundler-2.3.14/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /opt/hostedtoolcache/Ruby/3.3.5/x64/lib/ruby/gems/3.3.0/gems/bundler-2.3.[14](https://github.com/TheBookKnight/thebookknight.github.io/actions/runs/11905698311/job/33176602330#step:5:15)/lib/bundler/cli.rb:31:in `dispatch'
	from /opt/hostedtoolcache/Ruby/3.3.5/x64/lib/ruby/gems/3.3.0/gems/bundler-2.3.14/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /opt/hostedtoolcache/Ruby/3.3.5/x64/lib/ruby/gems/3.3.0/gems/bundler-2.3.14/lib/bundler/cli.rb:25:in `start'
	from /opt/hostedtoolcache/Ruby/3.3.5/x64/lib/ruby/gems/3.3.0/gems/bundler-2.3.14/exe/bundle:48:in `block in <top (required)>'
	from /opt/hostedtoolcache/Ruby/3.3.5/x64/lib/ruby/gems/3.3.0/gems/bundler-2.3.14/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	from /opt/hostedtoolcache/Ruby/3.3.5/x64/lib/ruby/gems/3.3.0/gems/bundler-2.3.14/exe/bundle:36:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/3.3.5/x64/bin/bundle:25:in `load'
	from /opt/hostedtoolcache/Ruby/3.3.5/x64/bin/bundle:25:in `<main>'
```

**Comment by TheBookKnight** [comment]
This seemed to solve the error above 
https://github.com/github/pages-gem/issues/399#issuecomment-301827749

Now, I'm getting this error
```
To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
            Source: /home/runner/work/thebookknight.github.io/thebookknight.github.io
       Destination: /home/runner/work/thebookknight.github.io/thebookknight.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
  Liquid Exception: Liquid error (/home/runner/work/thebookknight.github.io/thebookknight.github.io/_includes/section-projects.html line 36): Cannot sort a null object. included in /_layouts/default.html
/home/runner/work/thebookknight.github.io/thebookknight.github.io/vendor/bundle/ruby/3.3.0/gems/jekyll-3.10.0/lib/jekyll/filters.rb:22[9](https://github.com/TheBookKnight/thebookknight.github.io/actions/runs/11905826270/job/33176912702#step:5:10):in `sort': Liquid error (/home/runner/work/thebookknight.github.io/thebookknight.github.io/_includes/section-projects.html line 36): Cannot sort a null object. included  (Liquid::ArgumentError)
```

This helped resolve the error.
https://stackoverflow.com/a/76938250

**Comment by TheBookKnight** [comment]
Ok, so when I update root _config.yml, it updates the index.html after save.

**Comment by TheBookKnight** [comment]
Facing this error
> Branch "9-rebrand" is not allowed to deploy to github-pages due to environment protection rules.
